stages:
  read_data:
    cmd: python src/read_data.py data/yellow_tripdata_2024-11.parquet
    deps:
      - src/read_data.py
      - data/yellow_tripdata_2024-11.parquet
    outs:
      - pipelineOutput/processed/read_data.parquet

  process_data:
    cmd: python src/process_data.py pipelineOutput/processed/read_data.parquet
    deps:
      - src/process_data.py
      - pipelineOutput/processed/read_data.parquet
    outs:
      - pipelineOutput/processed/processed_data.parquet

  train_model_log_mlflow:
    cmd: python src/train_model.py pipelineOutput/processed/processed_data.parquet
    deps:
      - src/train_model.py
      - pipelineOutput/processed/processed_data.parquet
    outs:
      - models/dv.pkl
    # metrics:
    #   - metrics.json
